# Generated by Django 5.2.1 on 2025-06-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Telefon nomi')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('color', models.CharField(max_length=50, verbose_name='Rangi')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Chegirma narxi (so‘m)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi (so‘m)')),
                ('storage', models.IntegerField(verbose_name='Xotira (GB)')),
                ('ram', models.IntegerField(verbose_name='RAM (GB)')),
                ('os', models.CharField(max_length=50, verbose_name='Operatsion tizim')),
                ('image', models.ImageField(blank=True, null=True, upload_to='telefonlar/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Telefon',
                'ordering': ['-created_at'],
            },
        ),
    ]
